import C_healthy
from C_healthy import BMI, BMR, TDEE, WHR, LBM, BFP, BBW, IBW, MA, FFMI, RFM, VFR, BSA, VO2MAX, HSI, MMI, BFM

bmi = BMI(70, 1.75)
bmr = BMR("nam", 60, 1.75, 18)
tdee = TDEE("nam", 60, 1.75, 18, 3)
lbm = LBM("nam", 70, 1.75) 
ffmi = FFMI("nam", 60, 1.7)
rfm = RFM(85, 1.7) 
bfp = BFP("nam", 70, 1.75, 20)
ibw = IBW("nam", 1.75)
whr = WHR("nam", 85, 95)
bbw = BBW(60)
ma = MA("nam", 70, 1.7, 18)
vfr = VFR(85, 95)
bsa = BSA(1.7, 60)
vo2max = VO2MAX(110, 60)
hsi = HSI("nam", 60, 1.7, 18, 200, 110)
mmi = MMI("nam", 60, 1.7)
bfm = BFM("nam", 60, 1.7, 18)
print("BMI:", bmi)
print("BMR:", bmr)
print("TDEE:", tdee)
print("LBM:", lbm)
print("FFMI:", ffmi)
print("RFM:", rfm)
print("BFP:", bfp)
print("IBW:", ibw)
print("WHR:", whr)
print("BBW:", bbw)
print("MA:", ma)
print("VFR:", vfr)
print("BSA:", bsa)
print("VO2MAX:", vo2max)
print("HSI:", hsi)
print("MMI:", mmi)
print("BFM:", bfm)
print("\n__Version__:", C_healthy.__version__)